version: "3"
services:
  node:
    image: "node:alpine"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
    volumes:
      - ./:/home/node/app
    ports:
      - "${WEBSERVER_PORT:-8080}:3000"
    depends_on:
      - db
    command: "npm run start:prod"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
